[profile.default]
  build_info = true
  evm_version = "paris"
  extra_output = ["storageLayout"]
  ffi = true
  libs = ["lib"]
  optimizer = true
  optimizer_runs = 200
  out = "out"
  solc_version = "0.8.23"
  src = "src"
  via_ir = false

[profile.ci]
  fuzz = { runs = 256 }
  invariant = { runs = 1000 }
  via_ir = true

[rpc_endpoints]
  bsc = "${BSC_RPC_URL}"
  mainnet = "${MAINNET_RPC_URL}"

[fmt]
  line_length = 100
  multiline_func_header = "params_first"
  # wrap_comments = true

[profile.production]
  via_ir = true

  # See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
